#!/bin/bash -e

CONTROL_FILE=$1
CBI_FLWN_WKLY_MNTLY_FCT_FILE_LOOKUP_PATH=$2
CBI_FLWN_PREFINAL_FINAL_FCT_FILE_LOOKUP_PATH=$3

echo CONTROL_FILE=${CONTROL_FILE}
echo END_DATE=`date +"%Y-%m-%d %H:%M:%S"`
echo START_DATE=`tail -n 1 ${CONTROL_FILE} | cut -d";" -f2`

CBI_FLWN_WKLY_MNTLY_FCT_FILE_LOOKUP=`hdfs dfs -tail ${CBI_FLWN_WKLY_MNTLY_FCT_FILE_LOOKUP_PATH}`
CBI_FLWN_PREFINAL_FINAL_FCT_FILE_LOOKUP=`hdfs dfs -tail ${CBI_FLWN_PREFINAL_FINAL_FCT_FILE_LOOKUP_PATH}`

echo CBI_FLWN_WKLY_MNTLY_FCT_FILE_LOOKUP=${CBI_FLWN_WKLY_MNTLY_FCT_FILE_LOOKUP}
echo CBI_FLWN_PREFINAL_FINAL_FCT_FILE_LOOKUP=${CBI_FLWN_PREFINAL_FINAL_FCT_FILE_LOOKUP}

if [ "${CBI_FLWN_WKLY_MNTLY_FCT_FILE_LOOKUP}" == 0 -a "${CBI_FLWN_PREFINAL_FINAL_FCT_FILE_LOOKUP}" == 0 ]; then
        echo HELIX_RUN_IMPORT="TRUE"
else
        echo HELIX_RUN_IMPORT="FALSE"
fi