#!/bin/bash -e

CONTROL_FILE=$1
HDFS_CONTROL_FILE_KEY_LOOKUP=$2

echo CONTROL_FILE=${CONTROL_FILE}
echo HDFS_CONTROL_FILE_KEY_LOOKUP=${HDFS_CONTROL_FILE_KEY_LOOKUP}

START_ID=`tail -n 1 ${CONTROL_FILE} | cut -d";" -f2`
END_ID=`hdfs dfs -tail ${HDFS_CONTROL_FILE_KEY_LOOKUP}`

echo START_ID=${START_ID}
echo END_ID=${END_ID}
