#!/bin/bash -e

CONTROL_FILE=$1
START_ID=$2
END_ID=$3
HDFS_PATH=$4
CURRENT_TIMESTAMP=`date -u +"%s"`

echo CONTROL_FILE=${CONTROL_FILE}
echo START_ID=${START_ID}
echo END_ID=${END_ID}

echo "${START_ID};${END_ID}" > ${CONTROL_FILE}.${CURRENT_TIMESTAMP}
hdfs dfs -appendToFile ${CONTROL_FILE}.${CURRENT_TIMESTAMP} ${HDFS_PATH}/${CONTROL_FILE}
