#!/bin/bash -e

CONTROL_FILE=$1
SQOOP_PATH=$2
CBI_STATUS_FILE_LOOKUP=$3
CBI_FLWN_MNTLY_FCT_FILE_LOOKUP=$4
CBI_FLWN_WEKLY_FCT_FILE_LOOKUP=$5
CBI_FLWN_PREFINAL_FCT_FILE_LOOKUP=$6
CBI_FLWN_FINAL_FCT_FILE_LOOKUP=$7